# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\College\MiniProject\Mini-Project-group-8\UIDesign\UI\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(896, 608)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(690, 550, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 550, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 120, 151, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 261, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 341, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 251, 16))
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 180, 151, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 220, 451, 16))
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 240, 151, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 280, 581, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 300, 151, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 340, 651, 16))
        self.label_6.setObjectName("label_6")
        self.textEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 360, 151, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 400, 271, 16))
        self.label_7.setObjectName("label_7")
        self.textEdit_6 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_6.setGeometry(QtCore.QRect(20, 420, 151, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_7.setGeometry(QtCore.QRect(20, 480, 151, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 460, 821, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 221, 16))
        self.label_9.setObjectName("label_9")
        self.textEdit_8 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_8.setGeometry(QtCore.QRect(20, 60, 151, 31))
        self.textEdit_8.setObjectName("textEdit_8")

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(self.textEdit.clear) # type: ignore

        self.pushButton.clicked.connect(Dialog.close) # type: ignore

        self.pushButton_2.clicked.connect(self.textEdit_2.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.textEdit_3.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.textEdit_4.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.textEdit_5.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.textEdit_6.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.textEdit_7.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.textEdit_8.clear) # type: ignore
        self.textEdit.textChanged.connect(self.save_text)
        self.textEdit_2.textChanged.connect(self.save_text)
        self.textEdit_3.textChanged.connect(self.save_text)
        self.textEdit_4.textChanged.connect(self.save_text)
        self.textEdit_5.textChanged.connect(self.save_text)
        self.textEdit_6.textChanged.connect(self.save_text)
        self.textEdit_7.textChanged.connect(self.save_text)
        self.textEdit_8.textChanged.connect(self.save_text)

        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def save_text(self):
        text = self.textEdit.toPlainText()
        text_2 = self.textEdit_2.toPlainText()
        text_3 = self.textEdit_3.toPlainText()
        text_4 = self.textEdit_4.toPlainText()
        text_5 = self.textEdit_5.toPlainText()
        text_6 = self.textEdit_6.toPlainText()
        text_7 = self.textEdit_7.toPlainText()
        text_8 = self.textEdit_8.toPlainText()
        text_total = [text_8,'\n', text,'\n', text_2,'\n', text_3,'\n', text_4,'\n', text_5,'\n', text_6,'\n', text_7]
        with open('E:/College/MiniProject/Mini-Project-group-8/Job/textFile.txt', 'w') as file:
            file.writelines(text_total)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.pushButton_2.setText(_translate("Dialog", "Clear"))
        self.label.setText(_translate("Dialog", "Enter your sleep data"))
        self.label_2.setText(_translate("Dialog", "Time you went to sleep (in 24h clock) (E.g. 2200)"))
        self.label_3.setText(_translate("Dialog", "Time you woke up (in 24h Clock) (E.g. 0600)"))
        self.label_4.setText(_translate("Dialog", "Hours for which you woke up in the middle of the night trying to sleep (awakening) (E.g. 1)"))
        self.label_5.setText(_translate("Dialog", "Caffeine Consumption (0 = None | 25 = Little | 50 = Average | 75 = Above Average | 100 = High Consumption)"))
        self.label_6.setText(_translate("Dialog", "Alcohol Consumption (0 = None | 1 = Litte | 2 = Below Average | 3 = Average | 4 = Above Average | 5 = High Consumption )"))
        self.label_7.setText(_translate("Dialog", "Do You Smoke? (Yes / No)"))
        self.label_8.setText(_translate("Dialog", "Exercise Frequency (0 = No Exercise | 1 = Occasional | 2 = 3 days per week | 3 = 4 days per week | 4 = 5 days per week | 5 = 6 days per week )"))
        self.label_9.setText(_translate("Dialog", "Enter your age (E.g. 21)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
